services:
  redis:
      image: redis:7
      container_name: redis
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data
      restart: unless-stopped

  archive-api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  redis_data:
